### PR TITLE
-Removal of useless warnings; -Add inline mode option; -Solution proposal…

### PR DESCRIPTION
**Pull request by danielelidio**
-Removal of useless warnings
-Add inline mode option.
-Solution proposal for issue #28 (See: https://github.com/chymz/ng2-ckeditor/issues/28)

### CODE REVIEW

**Comment by hstarorg** [comment]
Thank you for your pull request!
Would you use two space indentation? Maybe you can use `editor config` plugin for your editor.

**Comment by danielelidio** [comment]
Yes, done! Please check it out.

**Comment by hstarorg** [comment]
Sorry, some file conflicts.
The `.vscode` and `lib` folder not needed.
I think you commited some unnecessary files.
Only update `src/ck-editor.component.ts` will be better.

**Comment by hstarorg** [comment]
There is the night in my country, I'll confirm at tomorrow, thank you!

**Comment by hstarorg** [comment]
@danielelidio This branch has conflicts that must be resolved
Please merge  the latest version before coding.

**Comment by danielelidio** [comment]
Hi, thanks for detecting it. I'm sorry for that mistake.

I'm having some trouble because when I run the either build or build:aot command on npm, the files created at the "lib" folder are with a very different structure than the original one. I even tried to set the "main" file at package.json pointing to the new structure "lib/src/index.js" and the "type" to "lib/src/index.d.ts" which makes the structure work fine but now, for some reason, when I try to import it to my project by doing: 

`import { CKEditorModule } from 'ngx-ckeditor';`

It does not find the module `ngx-ckeditor`.
I'm firstly trying to solve this problem and then I'll resolve the conflict.

**Comment by hstarorg** [comment]
Sorry, that's my muff. I update the project to fix that issues. Please merge and try again.

**Comment by Braste** [comment]
It is march now, will this eventually be merged soon?

**Comment by hstarorg** [comment]
@Braste Has many conflicts, I hope @danielelidio would update the pr.

**Pull request closed without merging**
